name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Update pip
      run: pip install --upgrade pip

    - name: Install pip packages
      run: |
            pip install antlr4-tools
            pip install conan==1.60

    - name: Download ANTLR
      run: make env/antlr

    - name: Prepare Conan
      run: |
            conan profile new default --detect
            conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Generate includes
      run: | 
            make includes/runtime 
            make includes/generated
    
    - name: Build
      run: make test

    - name: Test
      run: |
            build/bin/DoveCompiler tests/main.sysy -o tests/main.S
            build/bin/DoveCompiler tests/variables.sysy -o tests/variables.S
            build/bin/DoveCompiler tests/functionCall.sysy -o tests/functionCall.S
            build/bin/DoveCompiler tests/array.sysy -o tests/array.S

